// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	ID     string   `json:"id"`
	Orders []*Order `json:"orders"`
}

func (Customer) IsEntity() {}

type Order struct {
	ID       string     `json:"id"`
	Products []*Product `json:"products"`
	Buyer    *Customer  `json:"buyer"`
}

type Product struct {
	ID string `json:"id"`
}

func (Product) IsEntity() {}
